version: "3.9"
services:
  whatsapp-connector:
    build:
      context: ./whatsapp-connector/
    command: npm run start
    ports:
      - "8081:8081"
    environment:
      VERIFY_TOKEN: VERIFY_TOKEN
      WHATSAPP_TOKEN: VERIFY_TOKEN
      WHATSAPP_SEND_MESSAGE_API: WHATSAPP_SEND_MESSAGE_API
      CHATBOT_URL: http://chatbot:8080/api/message
      PORT: 8081
  chatbot:
    build:
      context: ./chatbot/
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: OPENAI_API_KEY
      PORT: 8080
