version: "3.9"
services:
  web:
    build:
      context: ./
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      VERIFY_TOKEN: VERIFY_TOKEN
      OPENAI_API_KEY: OPENAI_API_KEY
      WHATSAPP_TOKEN: WHATSAPP_TOKEN
      WHATSAPP_SEND_MESSAGE_API: WHATSAPP_SEND_MESSAGE_API
