version: "3.9"
services:
  whatsapp-connector:
    build:
      context: ./whatsapp-connector/
    command: npm run start
    environment:
      VERIFY_TOKEN: VERIFY_TOKEN
      WHATSAPP_TOKEN: VERIFY_TOKEN
      WHATSAPP_SEND_MESSAGE_API: WHATSAPP_SEND_MESSAGE_API
      CHATBOT_URL: http://chatbot:8080/api/message
      PORT: 8081
  chatbot:
    build:
      context: ./chatbot/
    command: npm run start
    environment:
      OPENAI_API_KEY: OPENAI_API_KEY
      PORT: 8080
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
