version: "3.9"
services:
  whatsapp-connector:
    image: mtwn105/whatsapp-connector:latest
    pull_policy: always
    command: npm run start
    environment:
      - VERIFY_TOKEN=%VERIFY_TOKEN%
      - WHATSAPP_TOKEN=%WHATSAPP_TOKEN%
      - WHATSAPP_SEND_MESSAGE_API=%WHATSAPP_SEND_MESSAGE_API%
      - CHATBOT_URL=%CHATBOT_URL%
      - PORT=8081
      - ES_HOST=http://elasticsearch:9200
  chatbot:
    image: mtwn105/whatsapp-chatbot:latest
    pull_policy: always
    command: npm run start
    environment:
      - OPENAI_API_KEY=%OPENAI_API_KEY%
      - PORT=8080
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:latest
    command: redis-server
  nginx:
    image: nginx:latest
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
