version: "3.9"
services:
  whatsapp-connector:
    build:
      context: ../whatsapp-connector
    command: npm run start
    environment:
      - VERIFY_TOKEN=%VERIFY_TOKEN%
      - WHATSAPP_TOKEN=%WHATSAPP_TOKEN%
      - WHATSAPP_SEND_MESSAGE_API=%WHATSAPP_SEND_MESSAGE_API%
      - CHATBOT_URL=%CHATBOT_URL%
      - PORT=8081
      - ES_HOST=http://elasticsearch:9200
    ports:
      - 8081:8081
  chatbot:
    build:
      context: ../chatbot
    command: npm run start
    environment:
      - OPENAI_API_KEY=%OPENAI_API_KEY%
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
